name: Workflow Controller

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README.md
      - .gitignore

  pull_request:
    branches: [ master ]

jobs:
  call-version-workflow:
    uses: ./.github/workflows/truevote-api-version.yml

  call-build-workflow:
    needs: call-version-workflow
    uses: ./.github/workflows/truevote-api-github.yml
