name: Bump Version

on:
  workflow_dispatch:

  workflow_call:

  workflow_run:
    workflows: ["Workflow Controller"]
    types: [completed]
    branches-ignore: [master]

jobs:
  tag_version:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: TrueVote
        DEFAULT_BUMP: patch
