name: Workflow Controller

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README.md
      - .gitignore

  pull_request:
    branches: [ master ]

jobs:
  call-version-workflow:
    uses: ./.github/workflows/truevote-api-version.yml

  call-build-workflow:
    runs-on: ubuntu-latest
    needs: call-version-workflow

    steps:
    - name: Invoke Build Workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Build, Test, Deploy
        token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}
